'use client';
import { useEffect, useState } from 'react';
type RequestRow = { id:string; requester_user_id:string; payer_user_id:string; amount:string; currency:string; description:string|null; status:string; expires_at:string|null; created_at:string; is_payer:boolean };
type Wallet = { id:string; currency:string; balance:string; status:string; public_code?:string };
export function PaymentRequests() {
  const [requests,setRequests]=useState<RequestRow[]>([]); const [wallets,setWallets]=useState<Wallet[]>([]); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState(''); const [review,setReview]=useState<{request:RequestRow;wallet:Wallet}|null>(null);
  const load=async()=>{ try { const [r,w]=await Promise.all([fetch('/api/payment-requests',{cache:'no-store'}),fetch('/api/wallet/currencies',{cache:'no-store'})]); if(r.ok)setRequests((await r.json()).paymentRequests); if(w.ok)setWallets((await w.json()).wallets); } catch { setError('Impossible de charger les demandes de paiement.'); } };
  useEffect(()=>{void load();},[]);
  const openReview=(r:RequestRow,walletId:string)=>{setError('');const wallet=wallets.find(w=>w.id===walletId);if(!wallet){setError('Choisissez un portefeuille avant de continuer.');return;}if(wallet.status!=='active'){setError('Ce portefeuille est inactif.');return;}if(wallet.currency!==r.currency){setError('La devise du portefeuille ne correspond pas à la demande.');return;}if(Number(wallet.balance)<Number(r.amount)){setError('Le solde disponible est insuffisant.');return;}setReview({request:r,wallet});};
  const act=async(id:string,action:'accept'|'reject',walletId?:string)=>{setBusy(id+action);setError('');try{const res=await fetch(`/api/payment-requests/${id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()+crypto.randomUUID()},body:action==='accept'?JSON.stringify({payerWalletId:walletId}):'{}'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Opération impossible');setReview(null);await load();}catch(e){setError(e instanceof Error?e.message:'Opération impossible');}finally{setBusy(null);}};
  const incoming=requests.filter(r=>r.is_payer&&r.status==='pending'); if(!incoming.length&&!error)return null;
  return <section className="payment-requests-section"><div className="transactions-heading"><div><small>PAIEMENTS</small><h2>Demandes reçues</h2></div><span>{incoming.length}</span></div>{error&&<p className="form-error" role="alert">{error}</p>}{review ? <div className="confirmationCard"><div className="confirmationWarning">VALIDATION AVANT EXÉCUTION</div><h3>Vérifiez le paiement</h3><dl className="confirmationGrid"><div><dt>Bénéficiaire</dt><dd>Demandeur FlowCash</dd></div><div><dt>Portefeuille débité</dt><dd>{review.wallet.public_code||review.wallet.currency}</dd></div><div><dt>Type</dt><dd>Paiement d’une demande</dd></div><div><dt>Montant</dt><dd>{Number(review.request.amount).toLocaleString('fr-FR')} {review.request.currency}</dd></div><div><dt>Frais</dt><dd>0 {review.request.currency}</dd></div><div><dt>Solde après</dt><dd>{(Number(review.wallet.balance)-Number(review.request.amount)).toLocaleString('fr-FR')} {review.wallet.currency}</dd></div></dl><p>{review.request.description||'Demande de paiement FlowCash'}</p><div className="payment-request-actions"><button type="button" onClick={()=>setReview(null)} disabled={!!busy}>Modifier</button><button type="button" onClick={()=>void act(review.request.id,'accept',review.wallet.id)} disabled={busy===review.request.id+'accept'}>{busy===review.request.id+'accept'?'Exécution sécurisée…':'Confirmer et payer'}</button></div></div> : <div className="payment-request-list">{incoming.map(r=>{const matching=wallets.filter(w=>w.status==='active');const defaultWallet=matching.find(w=>w.currency===r.currency)?.id||matching[0]?.id||'';return <article key={r.id} className="payment-request-card"><div><strong>{Number(r.amount).toLocaleString('fr-FR')} {r.currency}</strong><small>{r.description||'Demande de paiement'}</small></div><div className="payment-request-actions"><select defaultValue={defaultWallet} id={`wallet-${r.id}`}><option value="">Choisir le portefeuille</option>{matching.map(w=><option key={w.id} value={w.id}>{w.currency} · {Number(w.balance).toLocaleString('fr-FR')}</option>)}</select><button disabled={busy===r.id+'accept'} onClick={()=>{const el=document.getElementById(`wallet-${r.id}`) as HTMLSelectElement|null;if(!el?.value){setError('Choisissez un portefeuille avant de payer.');return;}openReview(r,el.value)}}>Vérifier et payer</button><button disabled={busy===r.id+'reject'} onClick={()=>void act(r.id,'reject')}>Refuser</button></div></article>})}</div>}</section>;
}
